// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiccWpJFg76ErMJ1GEuYzHNFW5zux0fEE',
    appId: '1:16166838351:web:9c02c4c62e0a55700f0a3a',
    messagingSenderId: '16166838351',
    projectId: 'phama-app-4ff05',
    authDomain: 'phama-app-4ff05.firebaseapp.com',
    storageBucket: 'phama-app-4ff05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0mNC001Ir8T89CKcXeaomLqZGQR9q7To',
    appId: '1:16166838351:android:fe4b3ff966b772580f0a3a',
    messagingSenderId: '16166838351',
    projectId: 'phama-app-4ff05',
    storageBucket: 'phama-app-4ff05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPYUp78dvJ0PA0-f56ess0WCxICnPe3A',
    appId: '1:16166838351:ios:ce257cfe659d3d4e0f0a3a',
    messagingSenderId: '16166838351',
    projectId: 'phama-app-4ff05',
    storageBucket: 'phama-app-4ff05.appspot.com',
    iosClientId: '16166838351-k77b45c6uoddeneh2qqeoctag337o8h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpPYUp78dvJ0PA0-f56ess0WCxICnPe3A',
    appId: '1:16166838351:ios:ce257cfe659d3d4e0f0a3a',
    messagingSenderId: '16166838351',
    projectId: 'phama-app-4ff05',
    storageBucket: 'phama-app-4ff05.appspot.com',
    iosClientId: '16166838351-k77b45c6uoddeneh2qqeoctag337o8h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharma',
  );
}
